source 'https://rubygems.org'

ruby2 = Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.0.0')

gem 'chromedriver-helper'
gem 'cucumber'
gem 'guard'
gem 'guard-cucumber'
gem 'page-object', '~> 1.2'
gem 'phantomjs'
gem 'pry-byebug' if ruby2
gem 'rspec'

group :test do
  gem 'rake'
end

# The following are required to deal with version conflicts
gem 'ruby_dep', '~> 1.3.0' if ruby2 && Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2.5')
gem 'listen', '~> 3.0.8'
gem 'watir-webdriver', '0.6.11'
