language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.2.3
  # - 2.3 not yet supported by travis
#before_install: gem install bundler -v 1.10.6
before_script: cd ruby && bundle install
script: bundle exec rake
