default:     -p chrome -p watir

phantomjs:   BROWSER=phantomjs -t @phantomjs,@any_browser,@calculator
chrome:      BROWSER=chrome    -t @chrome,@any_browser,@calculator
firefox:     BROWSER=firefox   -t @firefox,@any_browser,@calculator
ie:          BROWSER=ie        -t @ie,@any_browser,@calculator
safari:      BROWSER=safari    -t @safari,@any_browser,@calculator

watir:       DRIVER=watir    -t ~@selenium
selenium:    DRIVER=selenium -t ~@watir

html_report: -t ~@wip -p default --format progress --format html --out=features_report.html
